#!/bin/bash -eu

BAZEL=tools/bazelw

echo "🐢 Start fetching and installing third-party..."

# $BAZEL clean --expunge
$BAZEL build @Alamofire//:Alamofire
$BAZEL build @IQKeyboardManager//:IQKeyboardManager
$BAZEL build @ObjectMapper//:ObjectMapper
$BAZEL build @RxSwift//:RxSwift

exit 0